- name: sample ansible
  hosts: all
  tasks:
    - name: "Install Java"
      command: "{{ item }}"
      loop:
        - yum install java-1.8.0-openjdk-devel -y
        - java -version
        - java -version

    - name: "Install Jenkins"
      command: "{{ item }}"
      loop:
        - wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat/jenkins.repo
        - rpm --import https://pkg.jenkins.io/redhat/jenkins.io.key
        - yum install jenkins -y
        - systemctl enable jenkins
        - systemctl restart jenkins

    - name: sleep for 30 seconds and continue with play
      wait_for: timeout=30
      delegate_to: localhost

    - name: init password jenkin
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: print init password jenkins
      debug:
        var: result.stdout

    - name: "Install Maven"
      command: "{{ item }}"
      loop:
        - wget http://repos.fedorapeople.org/repos/dchen/apache-maven/epel-apache-maven.repo -O /etc/yum.repos.d/epel-apache-maven.repo
        - sed -i s/\$releasever/6/g /etc/yum.repos.d/epel-apache-maven.repo
        - yum install -y apache-maven git -y
        - mvn --version

    - name: "Install Ansible"
      command: "{{ item }}"
      loop:
        - sudo amazon-linux-extras install epel -y
        - sudo yum install ansible -y

